// Copyright (c) 2024 Victor Matia <vmatir@gmail.com>

namespace Vmr.Sdl2.Net.EventsManagement;

public enum EventType : uint
{
    FirstEvent = 0x0000,
    Quit = 0x0100,
    AppTerminating,
    AppLowMemory,
    AppWillEnterBackground,
    AppDidEnterBackground,
    AppWillEnterForeground,
    AppDidEnterForeground,
    LocaleChanged,
    DisplayEvent = 0x0150,
    WindowEvent = 0x0200,
    SysWmEvent,
    KeyDown = 0x0300,
    KeyUp,
    TextEditing,
    TextInput,
    KeymapChanged,
    TextEditingExt,
    MouseMotion = 0x0400,
    MouseButtonDown,
    MouseButtonUp,
    MouseWheel,
    JoystickAxisMotion = 0x0600,
    JoystickBallMotion,
    JoystickHatMotion,
    JoystickButtonDown,
    JoystickButtonUp,
    JoystickDeviceAdded,
    JoystickDeviceRemoved,
    JoystickBatteryUpdated,
    GameControllerAxisMotion = 0x0650,
    GameControllerButtonDown,
    GameControllerButtonUp,
    GameControllerDeviceAdded,
    GameControllerDeviceRemoved,
    GameControllerDeviceRemapped,
    GameControllerTouchpadDown,
    GameControllerTouchpadMotion,
    GameControllerTouchpadUp,
    GameControllerSensorUpdate,
    GameControllerUpdateCompleteReservedForSdl3,
    GameControllerSteamHandleUpdated,
    FingerDown = 0x0700,
    FingerUp,
    FingerMotion,
    DollarGesture = 0x0800,
    DollarRecord,
    MultiGesture,
    ClipboardUpdate = 0x0900,
    DropFile = 0x1000,
    DropText,
    DropBegin,
    DropComplete,
    AudioDeviceAdded = 0x1100,
    AudioDeviceRemoved,
    SensorUpdate = 0x1200,
    RenderTargetsReset = 0x2000,
    RenderDeviceReset,
    PollSentinel = 0x7F00,
    UserEvent = 0x8000,
    LastEvent = 0xFFFF
}
